### ISSUE TITLE
webpack-dev-server  security issue

### ISSUE THREAD

**Issue by metaclass-nl** [metaclass-nl/switch-language-example-globalize#1]
<pre>
│ High          │ Missing Origin Validation                           
│ Package       │ webpack-dev-server                              
│ Dependency of │ webpack-dev-server [dev]                 
│ Path          │ webpack-dev-server                                 
│ More info     │ https://nodesecurity.io/advisories/725     
</pre>

**Keep 'npm start' behind a firewall that only allows local access from the same machine!**

**Comment by metaclass-nl** [comment]
"webpack-dev-server": ">=3.1.11"  should be OK, but npm install emits:

npm WARN webpack-dev-server@3.1.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

furthermore webpack-cli must be intalled

but theb npm start results in:

/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/bin/webpack-dev-server.js:363
    throw err;
    ^

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/lib/Server.js:131:49)
    at new Server (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/lib/Server.js:144:5)
    at startDevServer (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/bin/webpack-dev-server.js:355:14)
    at processOptions (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
    at Object.<anonymous> (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack-dev-server/bin/webpack-dev-server.js:424:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by metaclass-nl** [comment]
Closed because the repository is archived
