### ISSUE TITLE
Error no formatters with babel 7

### ISSUE THREAD

**Issue by metaclass-nl** [metaclass-nl/switch-language-example-globalize#5]
branche babel7. Adapted config.

Error: 

84% module id optimization/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-webpack-plugin/GlobalizeCompilerHelper.js:77
        throw e;
        ^

Error: No formatters or parsers has been provided
    at compiler (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-compiler/lib/compile.js:220:9)
    at Object.compileExtracts (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-compiler/lib/compile-extracts.js:74:9)
    at GlobalizeCompilerHelper.compile (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-webpack-plugin/GlobalizeCompilerHelper.js:68:35)
    at chunk.mapModules (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:247:53)
    at Function.from (native)
    at Chunk.mapModules (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack/lib/Chunk.js:163:16)
    at compilation.chunks.filter.forEach (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:242:38)
    at Array.forEach (<anonymous>)
    at Compilation.compilation.plugin (/mcnl/nodejs/bookshop/skeleton/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:228:12)
    at Compilation.applyPlugins1 (/mcnl/nodejs/bookshop/skeleton/node_modules/tapable/lib/Tapable.js:75:14)
    at applyPluginsAsyncSeries (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack/lib/Compilation.js:629:9)
    at next (/mcnl/nodejs/bookshop/skeleton/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at next (/mcnl/nodejs/bookshop/skeleton/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/mcnl/nodejs/bookshop/skeleton/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at Compilation.applyPluginsAsyncSeries (/mcnl/nodejs/bookshop/skeleton/node_modules/tapable/lib/Tapable.js:206:13)

**Comment by metaclass-nl** [comment]
Closed because the repository is archived
